### PR TITLE
hide help command, resolves #20

### LINKED ISSUE #20: help consistency
why are there --help and 'integrity help'?  what is the difference?

### PR DESCRIPTION
**Pull request by ekristen**
resolves #20

### CODE REVIEW

**Comment by mark-hallman** [comment]
What is being hidden?  The `--help` and the `-h`?  or the `integrity help`? I don't see that this is stated in the two issues.  Sorry if I missed it.

**Comment by ekristen** [comment]
Removes the help command and leaves the help flags.

**Comment by mark-hallman** [comment]
Got it, thanks.

-Mark

**Pull request merged**
